### ISSUE TITLE
What framework shall we use for development?

### ISSUE THREAD

**Issue by alexseif** [Law3andakDam/introduction#2]

**Comment by alexseif** [comment]
I vote for Symfony for our framework.
And bootstrap for our CSS.

**Comment by OmarAbdallah95** [comment]
Symfony new for me , so I vote laravel

**Comment by MuohamedNaser** [comment]
I used CodeIgniter before but it may not serve our purpose. both Symfony and Laravel new for me. so i do not have clear idea about the best thing to our case

**Comment by alexseif** [comment]
Laravel is pretty much symfony based.. Learning a new tool might be a factor, but I have no arguments for or against, and for time purposes, I'm going to simply pull rank
